AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Task Management API'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

Resources:
  TaskManagementAPI:
    Type: AWS::ECS::Service
    Properties:
      # Add your ECS service configuration here
      ServiceName: !Sub task-management-api-${Environment}
      # Other properties...

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      # Add your task definition configuration here
      Family: !Sub task-management-api-${Environment}
      # Other properties...

  # Add other resources as needed (VPC, Security Groups, etc.)

Outputs:
  APIEndpoint:
    Description: API Endpoint URL
    Value: !Sub https://${TaskManagementAPI}.execute-api.${AWS::Region}.amazonaws.com/${Environment}