TargetGroup:
  Type: AWS::ElasticLoadBalancingV2::TargetGroup
  Properties:
    TargetType: ip
    Port: 3000
    Protocol: HTTP
    VpcId: !Ref VPC
    HealthCheckPath: /api/tasks
    HealthCheckIntervalSeconds: 60
    HealthCheckTimeoutSeconds: 30
    HealthyThresholdCount: 2
    UnhealthyThresholdCount: 5
    Matcher:
      HttpCode: '200,404'