AWSTemplateFormatVersion: '2010-09-09'
Description: 'Task Management API Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues: [prod, dev]
  DBUsername:
    Type: String
    NoEcho: true
  DBPassword:
    Type: String
    NoEcho: true
  DBName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select an existing VPC
  PublicSubnet1Id:
    Type: AWS::EC2::Subnet::Id
    Description: Select first public subnet
  PublicSubnet2Id:
    Type: AWS::EC2::Subnet::Id
    Description: Select second public subnet

Resources:
  # Database Resources
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Task Management API database
      SubnetIds: 
        - !Ref PublicSubnet1Id
        - !Ref PublicSubnet2Id

  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS instance
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref ContainerSecurityGroup

  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName
      Engine: postgres
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBInstanceClass: db.t3.micro
      AllocatedStorage: '20'
      PubliclyAccessible: true
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups: 
        - !Ref DatabaseSecurityGroup
      BackupRetentionPeriod: 7
      Port: 5432
    DeletionPolicy: Snapshot

  # Security Groups
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for API container
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

  # ECS Resources
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AWS::StackName}-task
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/${AWS::StackName}-ExecRole-${AWS::Region}-${AWS::AccountId}
      TaskRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/${AWS::StackName}-TaskRole-${AWS::Region}-${AWS::AccountId}
      ContainerDefinitions:
        - Name: api
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/task-management-api-prod:latest
          PortMappings:
            - ContainerPort: 3000
          Environment:
            - Name: DB_HOST
              Value: !GetAtt Database.Endpoint.Address
            - Name: DB_PORT
              Value: !GetAtt Database.Endpoint.Port
            - Name: DB_USERNAME
              Value: !Ref DBUsername
            - Name: DB_PASSWORD
              Value: !Ref DBPassword
            - Name: DB_NAME
              Value: !Ref DBName
            - Name: NODE_ENV
              Value: production
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub /ecs/${AWS::StackName}-${Environment}
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  Service:
    Type: AWS::ECS::Service
    DependsOn: Database
    Properties:
      ServiceName: task-management-api
      Cluster: !Sub ${AWS::StackName}-${Environment}-${AWS::Region}
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref PublicSubnet1Id
            - !Ref PublicSubnet2Id
          SecurityGroups:
            - !Ref ContainerSecurityGroup

Outputs:
  DatabaseEndpoint:
    Description: Database endpoint
    Value: !GetAtt Database.Endpoint.Address
  DatabasePort:
    Description: Database port
    Value: !GetAtt Database.Endpoint.Port
  ContainerSecurityGroup:
    Description: Security Group for the containers
    Value: !Ref ContainerSecurityGroup
  ServiceName:
    Description: Name of the ECS Service
    Value: !Ref Service